### PR TITLE
Enumerate and require chip def files dynamically

### PR DESCRIPTION
**Pull request by joshperry**
Love this set of AVR tools for node!

I'd like to add xmega part defs to this repo. Do you have a script you used to automate conversion from the avrdude format to your json format?

### CODE REVIEW

**Comment by noopkat** [comment]
@joshperry so I may have read the email notification for this when I was half asleep one morning last week, and thought I dreamed about it instead. Typical me, sorry! I just found this tonight by listing all PR's on any of my repos.

This PR is so fabulous, thank you!! I learned new tricks and this is much easier on future contributors 💥

Merging, will publish shortly.

PS. for xmega - I have a rather ugly translation repo I can give you private access to. Modifications to the 'scriptagheddon' I wrote will be necessary for the xmega specs because it uses PDI, not ISP. Let me know!

**Comment by joshperry** [comment]
You're welcome. Just been poking around node hardware libs and ran into these. I'm a bit of an avr fanboi, particularly the xmegas.

They may eventually go the way of the dodo with the arm m-series and other SoCs eating their lunch, but for now we're going to keep using them!

Does your isp code handle PDI or is that going to need some work too? We use the jtagicemkii which apparently uses a slightly modified stk500 protocol, but that's not terribly important. Our production flashing is handled by our CM and we can use an ispmkii or similar for our in-house short run work.

**Comment by joshperry** [comment]
Errr, so yeah. I'm definitely interested in this end-of-times beast if it'll save me some work!

**Comment by noopkat** [comment]
For now, AVRGirl is only aiming to support ISP. Not ruling out JTAG or PDI in the future though (although I'd have to revisit my backronym slightly haha). Physical testing of what it has now takes priority before adding any new debug/comm technology standards.

This doesn't mean that AVRGirl chips json can't start supporting xmega though, as long as I communicate what AVRGirl itself supports specifically. Having a brief look, the json spec design may have to have some additions (and the existing translation file might not be of much use but still handy to reference perhaps). There's a chance it can all fit without breaking backwards compatibility :grin:

**Comment by joshperry** [comment]
Absolutely understandable. Not looking to redefine or break any existing system.

AVRs and node are just a couple of my favorite things.

I don't think adding debug support is critical (though stepping through sketches would be pretty rad). I'd just like to be able to flash my xmegas using node.

General In-circuit pRogramming tooL? 😬

**Pull request merged**
